services:
  configserver:
    image: "azakyd/configserver:s6"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    networks:
      - eazybank

  accounts:
    image: "azakyd/accounts:s6"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    networks:
      - eazybank

  loans:
    image: "azakyd/loans:s6"
    container_name: loans-ms
    ports:
      - "8090:8090"
    networks:
      - eazybank

  cards:
    image: "azakyd/cards:s6"
    container_name: cards-ms
    ports:
      - "9000:9000"
    networks:
      - eazybank

networks:
  eazybank:
    driver: bridge
